rasterizer_cpp:
	g++ -o rasterizer Camera.cpp Color.cpp Helpers.cpp Matrix4.cpp Model.cpp Rotation.cpp Scaling.cpp Scene.cpp tinyxml2.cpp Translation.cpp Triangle.cpp Vec3.cpp Vec4.cpp Main.cpp 

clean:
	rm -rf *.ppm *.png ./rasterizer
